"""Canonical token registry.

Single source of truth for all valid tokens in the protocol domain.
Derived from the ontology normalization definitions so the registry
stays consistent with the runtime fact-generation logic.
"""

from __future__ import annotations

from typing import Any

from src.ontology.normalize import (
    BMI_THRESHOLDS,
    DIAGNOSIS_SUPERTYPE_EXPANSIONS,
    FRONTEND_ACTIONS,
    FRONTEND_COMORBIDITIES,
    FRONTEND_DIAGNOSES,
    FRONTEND_PHYSIOLOGIC_STATES,
    GESTATIONAL_AGE_THRESHOLDS,
    MATERNAL_AGE_THRESHOLDS,
)

VERDICTS = ("Obligated", "Allowed")


# ---------------------------------------------------------------------------
#  Token lists (used for validation in Build pages)
# ---------------------------------------------------------------------------

def _build_action_tokens() -> list[str]:
    return sorted({defn.token for defn in FRONTEND_ACTIONS.values()})


def _build_diagnosis_tokens() -> list[str]:
    tokens: set[str] = set()
    for defn in FRONTEND_DIAGNOSES.values():
        tokens.add(defn.diagnosis_token)
    for parent_set in DIAGNOSIS_SUPERTYPE_EXPANSIONS.values():
        tokens.update(parent_set)
    return sorted(tokens)


def _build_diagnosis_attribute_tokens() -> list[str]:
    tokens: set[str] = set()
    for defn in FRONTEND_DIAGNOSES.values():
        for attr_token, _label in defn.diagnosis_attribute_by_id.values():
            tokens.add(attr_token)
    return sorted(tokens)


def _build_context_tokens() -> list[str]:
    tokens: set[str] = set()

    for defn in FRONTEND_COMORBIDITIES.values():
        tokens.add(defn.token)
    for defn in FRONTEND_PHYSIOLOGIC_STATES.values():
        tokens.add(defn.token)

    for threshold in GESTATIONAL_AGE_THRESHOLDS:
        tokens.add(f"Ctx.GA_>={threshold}w")

    tokens.add(f"Ctx.MaternalAge_<{MATERNAL_AGE_THRESHOLDS[0]}y")
    for threshold in MATERNAL_AGE_THRESHOLDS:
        tokens.add(f"Ctx.MaternalAge_>={threshold}y")

    tokens.add(f"Ctx.BMI_<{BMI_THRESHOLDS[0]}")
    for threshold in BMI_THRESHOLDS:
        tokens.add(f"Ctx.BMI_>={threshold}")

    return sorted(tokens)


def _build_special_tokens() -> list[str]:
    """Tokens that appear in seed data but aren't generated by the UI normalizer."""
    return sorted({"Dx.FetalDemise", "Ctx.GA_<34w"})


# ---------------------------------------------------------------------------
#  Input options (used by the Inputs page for labels + ids)
# ---------------------------------------------------------------------------

def _build_input_options() -> dict[str, Any]:
    diagnoses_list: list[dict[str, Any]] = []
    for fid, defn in FRONTEND_DIAGNOSES.items():
        attrs = [
            {"id": attr_id, "label": label}
            for attr_id, (_, label) in defn.diagnosis_attribute_by_id.items()
        ]
        diagnoses_list.append({
            "id": fid,
            "label": defn.label,
            "diagnosisToken": defn.diagnosis_token,
            "availableAttributes": attrs,
        })
    diagnoses_list.sort(key=lambda d: d["label"])

    comorbidities_list = sorted(
        [{"id": fid, "label": defn.label} for fid, defn in FRONTEND_COMORBIDITIES.items()],
        key=lambda d: d["label"],
    )
    physiologic_list = sorted(
        [{"id": fid, "label": defn.label} for fid, defn in FRONTEND_PHYSIOLOGIC_STATES.items()],
        key=lambda d: d["label"],
    )
    actions_list = [
        {"id": fid, "label": defn.label}
        for fid, defn in FRONTEND_ACTIONS.items()
    ]

    return {
        "diagnoses": diagnoses_list,
        "comorbidities": comorbidities_list,
        "physiologicStates": physiologic_list,
        "clinicalActions": actions_list,
        "gestationalAgeMarks": list(GESTATIONAL_AGE_THRESHOLDS),
        "maternalAgeMarks": list(MATERNAL_AGE_THRESHOLDS),
        "bmiMarks": list(BMI_THRESHOLDS),
    }


# ---------------------------------------------------------------------------
#  Public API
# ---------------------------------------------------------------------------

def build_token_registry() -> dict[str, Any]:
    """Return the full token registry grouped by category."""
    actions = _build_action_tokens()
    diagnoses = _build_diagnosis_tokens()
    diagnosis_attributes = _build_diagnosis_attribute_tokens()
    context = _build_context_tokens()
    special = _build_special_tokens()

    facts = sorted(set(diagnoses + diagnosis_attributes + context + special))

    return {
        "actions": actions,
        "verdicts": list(VERDICTS),
        "facts": facts,
        "diagnoses": diagnoses,
        "diagnosisAttributes": diagnosis_attributes,
        "context": context,
        "inputOptions": _build_input_options(),
    }
